import YAML from "yaml";
import type { ActionBox } from "../types.js";

const ACTIONBOX_HEADER = `# ACTIONBOX.md — Behavioral Contract
# Auto-generated by ActionBox. Do not edit manually unless marking as reviewed.
`;

/**
 * Parse an ACTIONBOX.md file's YAML content into an ActionBox object.
 * The file is expected to have a YAML block between --- fences.
 */
export function parseActionBox(content: string): ActionBox {
  const yamlMatch = content.match(/---\n([\s\S]*?)\n---/);
  if (!yamlMatch) {
    throw new Error("No YAML frontmatter found in ACTIONBOX.md");
  }
  const parsed = YAML.parse(yamlMatch[1]) as ActionBox;

  // Default new optional fields for backward compatibility
  if (parsed.behavior) {
    parsed.behavior.alwaysDo ??= [];
    parsed.behavior.principles ??= [];
  }

  parsed.allowedCapabilities ??= [];
  parsed.deniedCapabilities ??= [];

  return parsed;
}

/**
 * Serialize an ActionBox object to ACTIONBOX.md format.
 */
export function serializeActionBox(box: ActionBox): string {
  const yamlContent = YAML.stringify(box, {
    lineWidth: 120,
    defaultKeyType: "PLAIN",
    defaultStringType: "PLAIN",
  });
  return `${ACTIONBOX_HEADER}\n---\n${yamlContent}---\n`;
}

/**
 * Extract just the YAML data from an ACTIONBOX.md string without full parsing.
 */
export function extractYaml(content: string): Record<string, unknown> | null {
  const yamlMatch = content.match(/---\n([\s\S]*?)\n---/);
  if (!yamlMatch) return null;
  return YAML.parse(yamlMatch[1]) as Record<string, unknown>;
}
